module.exports = {
  UDP_PORT: 41234,

  MSG: {
    SESSION_OFFER: "SESSION_OFFER",
    JOIN_REQUEST: "JOIN_REQUEST",
    JOIN_ACCEPTED: "JOIN_ACCEPTED",
    START_SESSION: "START_SESSION",
    END_SESSION: "END_SESSION"
  }
};
